// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Mon Nov 25 11:28:59 2024

ControlUnit ControlUnit_inst
(
	.ClearAll(ClearAll_sig) ,	// input  ClearAll_sig
	.Clock(Clock_sig) ,	// input  Clock_sig
	.value(value_sig) ,	// input [N-1:0] value_sig
	.trig(trig_sig) ,	// input  trig_sig
	.ClearEntry_signal(ClearEntry_signal_sig) ,	// input  ClearEntry_signal_sig
	.reset(reset_sig) ,	// output  reset_sig
	.LoadA(LoadA_sig) ,	// output  LoadA_sig
	.LoadB(LoadB_sig) ,	// output  LoadB_sig
	.LoadR(LoadR_sig) ,	// output  LoadR_sig
	.AddSub(AddSub_sig) ,	// output  AddSub_sig
	.IUAU(IUAU_sig) ,	// output  IUAU_sig
	.ClearEntry_signal_out(ClearEntry_signal_out_sig) 	// output  ClearEntry_signal_out_sig
);

defparam ControlUnit_inst.N = 4;
defparam ControlUnit_inst.S0 = 'b000;
defparam ControlUnit_inst.S1 = 'b001;
defparam ControlUnit_inst.S2 = 'b010;
defparam ControlUnit_inst.S3 = 'b011;
defparam ControlUnit_inst.S4 = 'b100;
